os:
  - osx
language: c
compiler:
  - clang
  - gcc
env:
  - EXTRA=
before_install:
  - env
  - brew update
  - brew tap adilinden/homebrew-asterisk
  # manually tap versions so brew deps will work
  - brew tap homebrew/versions
  - comm -12 <(brew deps ./asterisk.rb) <(brew outdated) | xargs brew upgrade
  - brew ls
install:
  - brew install --only-dependencies ./asterisk.rb
script:
  - brew reinstall ./asterisk.rb --verbose --with-dev-mode --with-${CC} ${EXTRA}
